// @NOTICE This file is generated by sav.

module.exports = {
  ResHomeIndex: [
    {
      title: "模拟数据1",
      props: {
        welcome: "😄"
      }
    },
    {
      title: "模拟数据2",
      props: {
        welcome: "喝喝"
      }
    }
  ],
  ResUserNavMenu: [
    {
      title: "模拟数据1",
      props: {
        menus: [
          {
            title: "模拟菜单-主页",
            url: "/"
          },
          {
            title: "模拟菜单-关于",
            url: "/about"
          }
        ]
      }
    }
  ]
}
