// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  moduleName: "Account",
  moduleGroup: "Page",
  props: {
    view: "vue",
    layout: "UserLayout"
  },
  routes: [
    {
      actionName: "login",
      middlewares: [
        {
          name: "title",
          props: "登录"
        },
        {
          name: "route",
          props: {
            method: "GET"
          }
        }
      ]
    },
    {
      actionName: "postLogin",
      middlewares: [
        {
          name: "vue",
          props: {
            component: "Account/AccountLogin"
          }
        },
        {
          name: "title",
          props: "登录"
        },
        {
          name: "req",
          props: {
            props: {
              username: "String",
              password: "String"
            }
          }
        },
        {
          name: "route",
          props: {
            method: "POST"
          }
        }
      ]
    },
    {
      actionName: "register",
      middlewares: [
        {
          name: "title",
          props: "注册"
        },
        {
          name: "route",
          props: {
            method: "GET"
          }
        },
        {
          name: "res",
          props: {
            name: "AccountRegister",
            props: {
              accountRegisterStruct: "AccountRegisterStruct"
            },
            refs: {
              AccountRegisterStruct: {
                name: "AccountRegisterStruct",
                props: {
                  username: "String",
                  email: "String",
                  password: "String"
                }
              }
            }
          }
        }
      ]
    },
    {
      actionName: "postRegister",
      middlewares: [
        {
          name: "vue",
          props: {
            component: "Account/AccountRegister"
          }
        },
        {
          name: "title",
          props: "注册"
        },
        {
          name: "req",
          props: "AccountRegisterStruct"
        },
        {
          name: "route",
          props: {
            method: "POST"
          }
        },
        {
          name: "res",
          props: "ResAccountRegister"
        }
      ]
    }
  ]
}
