// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  moduleName: "Article",
  moduleGroup: "Page",
  props: {
    view: "vue",
    layout: "UserLayout"
  },
  routes: [
    {
      actionName: "posts",
      middlewares: [
        {
          name: "meta",
          props: {
            keywords: "关键字列表",
            description: "页面描述"
          }
        },
        {
          name: "title",
          props: "文章列表"
        },
        {
          name: "route",
          props: {
            method: "GET"
          }
        },
        {
          name: "res",
          props: {
            name: "ResArticleList",
            props: {
              articles: "Array<ArticleItem>"
            },
            refs: {
              ArticleItem: {
                name: "ArticleItem",
                props: {
                  id: "Number",
                  title: "String",
                  content: "String"
                }
              }
            }
          }
        }
      ]
    },
    {
      actionName: "view",
      middlewares: [
        {
          name: "req",
          props: {
            props: {
              aid: "String"
            }
          }
        },
        {
          name: "route",
          props: {
            method: "GET",
            path: "view/:aid"
          }
        },
        {
          name: "res",
          props: {
            name: "ResArtilceView",
            props: {
              article: "ArticleItem"
            }
          }
        }
      ]
    },
    {
      actionName: "modify",
      middlewares: [
        {
          name: "vue",
          props: {
            component: "Article/ArticleModify"
          }
        },
        {
          name: "auth"
        },
        {
          name: "route",
          props: {
            method: "GET",
            path: "modify/:id?"
          }
        }
      ]
    },
    {
      actionName: "update",
      middlewares: [
        {
          name: "vue",
          props: {
            component: "Article/ArticleModify"
          }
        },
        {
          name: "auth"
        },
        {
          name: "route",
          props: {
            method: "POST",
            path: "update/:aid"
          }
        }
      ]
    }
  ]
}
