// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  routes: {
    copyRight: {
      method: "GET",
      response: {
        props: {
          copyright: "String"
        }
      }
    },
    userInfo: {
      method: "GET",
      response: {
        props: {
          userInfo: "UserInfo"
        },
        refs: {
          Role: {
            name: "Role",
            default: "guest",
            enums: [
              {
                key: "user",
                value: "user"
              },
              {
                key: "guest",
                value: "guest"
              },
              {
                key: "admin",
                value: "admin"
              }
            ]
          },
          UserInfo: {
            props: {
              name: "String",
              id: "Number",
              role: "Role"
            }
          }
        }
      }
    },
    navMenu: {
      method: "GET",
      response: {
        props: {
          menus: "Array<NavMenuItem>"
        },
        refs: {
          NavMenuItem: {
            props: {
              title: "String",
              url: "String"
            }
          }
        }
      }
    }
  }
}
