// @NOTICE This file is generated by sav.

// npm i -D vue vue-router
// 全局的VUE组件需要在这里注册
// 其他需要用Vue的需要从这里引入
import VueRouter from 'vue-router'
import Vue from 'vue'

Vue.use(VueRouter)

export {Vue}
export {VueRouter}
