// @NOTICE This file is generated by sav.

// npm i -D vue-server-renderer
import {Vue, VueRouter} from './server-plugins.js'
import routes from './routes.js'
import App from './App.vue'
import {createRenderer} from 'vue-server-renderer'

let router = new VueRouter(Object.assign({
  mode: 'history',
  routes,
  linkActiveClass: 'is-active'
}))

let vm = new Vue(Object.assign({
  router
}, App))

export default {
  router,
  vm,
  createRenderer,
  renderOptions: {
  }
}
