// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  layout: "User",
  routes: {
    posts: {
      method: "GET",
      title: "文章列表",
      response: {
        props: {
          articles: "Array<ArticleItem>"
        },
        refs: {
          ArticleItem: {
            props: {
              id: "Number",
              title: "String",
              content: "String"
            }
          }
        }
      }
    },
    view: {
      method: "GET",
      path: "/articles/:aid",
      response: {
        props: {
          article: "ArticleItem"
        }
      },
      request: {
        props: {
          aid: "String"
        }
      }
    },
    modify: {
      method: "POST",
      path: "modify/:id?",
      auth: true,
      component: "Article/ArticleModify"
    },
    update: {
      method: "POST",
      path: "update/:aid",
      auth: true,
      component: "Article/ArticleModify"
    }
  }
}
