<?php
// @NOTICE This file is generated by sav.

class Article
{
  public function posts () {

  }
  public function modify () {

  }
  public function update () {

  }
  public function view () {

  }
}
