<?php
// @NOTICE This file is generated by sav.
use Sav;
namespace Sav\Actions;

class Home
{
  public function about () {

  }
  public function userInfo () {

  }
  public function navMenu () {

  }
  public function profile () {

  }
  public function index () {

  }
}
