// @NOTICE This file is generated by sav.

module.exports = class Home {
  async index () {
    return await Promsie.all([])
  }
  about () {

  }
  async profile () {

  }
  userInfo () {

  }
  async navMenu () {

  }
}
