// @NOTICE This file is generated by sav.

module.exports = class Home {
  async index () {

  }
  async about () {

  }
  async profile () {

  }
  async userInfo () {

  }
  async navMenu () {

  }
}
