// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  ResHomeIndex: [
    {
      title: "模拟数据1",
      props: {
        welcome: "😄"
      }
    },
    {
      title: "模拟数据2",
      props: {
        welcome: "喝喝"
      }
    }
  ]
}
