// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  ResUserNavMenu: [
    {
      title: "模拟数据1",
      props: {
        menus: [
          {
            title: "模拟菜单-主页",
            url: "/"
          },
          {
            title: "模拟菜单-关于",
            url: "/about"
          }
        ]
      }
    }
  ]
}
