// @NOTICE This file is generated by sav-cli 

module.exports = {
  moduleName: "User",
  moduleGroup: "Layout",
  uri: "UserLayout",
  props: {},
  routes: [
    {
      actionName: "copyRight",
      uri: "UserLayout.copyRight",
      middlewares: [
        {
          name: "invoke"
        },
        {
          name: "res",
          props: {
            props: {
              copyright: "String"
            }
          }
        }
      ]
    },
    {
      actionName: "userInfo",
      uri: "UserLayout.userInfo",
      middlewares: [
        {
          name: "invoke"
        },
        {
          name: "res",
          props: {
            props: {
              userInfo: "UserInfo"
            },
            refs: {
              Role: {
                name: "Role",
                enums: [
                  {
                    key: "user",
                    value: "user"
                  },
                  {
                    key: "guest",
                    value: "guest"
                  },
                  {
                    key: "admin",
                    value: "admin"
                  }
                ]
              },
              UserInfo: {
                props: {
                  name: "String",
                  id: "Number",
                  role: "Role"
                }
              }
            }
          }
        }
      ]
    },
    {
      actionName: "userNavMenu",
      uri: "UserLayout.userNavMenu",
      middlewares: [
        {
          name: "invoke"
        },
        {
          name: "res",
          props: {
            props: {
              menus: "Array<NavMenuItem>"
            },
            refs: {
              NavMenuItem: {
                props: {
                  title: "String",
                  url: "String"
                }
              }
            }
          }
        }
      ]
    }
  ],
  SavRoute: {
    uri: "UserLayout",
    path: "/user",
    childs: [],
    parents: []
  }
}
