// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  ReqAccountLogin: {
    props: {
      userId: "String",
      password: "String"
    }
  },
  Sex: {
    enums: [
      {
        key: "male",
        value: 1
      },
      {
        key: "female",
        value: 2
      }
    ]
  }
}
