import {createIndex, createRoot} from './applyUtil.js'
import {writeFileAsync, mkdirAsync} from './sav/util/file.js'
import {resolve} from 'path'
import JSON5 from 'json5'

const noticeString = '// @NOTICE This file is generated by sav-cli.\n\n'
const eslintQuotes = '/* eslint quotes: ["off"] */\n'
const applyTitle = '[Contract]'

function createContract (groupDir, module, moduleName, dest, json) {
  return Promise.resolve().then(async () => {
    let dir = resolve(dest, groupDir)
    await mkdirAsync(dir)
    if (json) {
      let jsonFile = resolve(dir, moduleName + '.json')
      console.log(`${applyTitle}[create] `, jsonFile)
      await writeFileAsync(jsonFile, JSON.stringify(module, null, 2))
    } else {
      let jsFile = resolve(dir, moduleName + '.js')
      console.log(`${applyTitle}[create] `, jsFile)
      let jsData = JSON5.stringify(module, null, 2)
      jsData = `${noticeString}${eslintQuotes}module.exports = ${jsData}\n`
      await writeFileAsync(jsFile, jsData)
    }
  })
}

function createContracts (groups, program) {
  let tasks = []
  for (let moduleGroup in groups) {
    let group = groups[moduleGroup]
    for (let moduleName in group) {
      let module = group[moduleName]
      tasks.push(createContract(moduleGroup, module, moduleName, program.dest, program.json))
    }
    tasks.push(createIndex(moduleGroup, group, program.dest, false, moduleGroup === 'schema' ||
      moduleGroup === 'mock'))
  }
  tasks.push(createRoot(groups, program.dest))
  return Promise.all(tasks)
}

export function applyContract (groups, program) {
  return createContracts(groups, program)
}
