// @NOTICE This file is generated by sav-cli.

module.exports = {
  api: require('./api'),
// #if IS_MOCK
  mock: require('./mock'),
// #endif
  page: require('./page'),
  schema: require('./schema')
}
