// @NOTICE This file is generated by sav-cli.

module.exports = {
  api: require('./api'),
  layout: require('./layout'),
  mock: require('./mock')/* IS_MOCK */,
  page: require('./page'),
  schema: require('./schema')
}
