'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var VueRouter = _interopDefault(require('vue-router'));
var Vue = _interopDefault(require('vue'));
var savFlux = require('sav-flux');
var Article = _interopDefault(require('Article/Article.vue'));
var ArticlePosts = _interopDefault(require('Article/ArticlePosts.vue'));
var ArticleView = _interopDefault(require('Article/ArticleView.vue'));
var ArticleModify = _interopDefault(require('Article/ArticleModify.vue'));
var Home = _interopDefault(require('Home/Home.vue'));
var HomeIndex = _interopDefault(require('Home/HomeIndex.vue'));
var HomeAbout = _interopDefault(require('Home/HomeAbout.vue'));
var HomeProfile = _interopDefault(require('Home/HomeProfile.vue'));
var vueServerRenderer = require('vue-server-renderer');

// @NOTICE This file is generated by sav.

// npm i -D vue vue-router sav-flux
// 全局的VUE组件需要在这里注册
// 其他需要用Vue的需要从这里引入
Vue.use(VueRouter);
Vue.use(savFlux.FluxVue);

// @NOTICE This file is generated by sav.

var routes = [{
  component: Article,
  path: "Article",
  children: [{
    component: ArticlePosts,
    name: "ArticlePosts",
    path: "Posts"
  }, {
    component: ArticleView,
    name: "ArticleView",
    path: "/articles/:aid"
  }, {
    component: ArticleModify,
    name: "ArticleModify",
    path: "modify/:id?"
  }, {
    component: ArticleModify,
    name: "ArticleUpdate",
    path: "update/:aid"
  }]
}, {
  component: Home,
  path: "",
  children: [{
    component: HomeIndex,
    name: "HomeIndex",
    path: "/"
  }, {
    component: HomeAbout,
    name: "HomeAbout",
    path: "About"
  }, {
    component: HomeProfile,
    name: "HomeProfile",
    path: "profile/:uid"
  }]
}];

var App = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { attrs: { "id": "app" } }, [_c('router-view', { staticClass: "page-container" })], 1);
  },
  staticRenderFns: [],
  name: 'App',
  getters: [],
  actions: []
};

// @NOTICE This file is generated by sav.

// npm i -D vue-server-renderer
let router = new VueRouter(Object.assign({
  mode: 'history',
  routes,
  linkActiveClass: 'is-active'
}));

let flux = new savFlux.Flux({
  strict: true
});

let vm = new Vue(Object.assign({
  vaf: new savFlux.FluxVue({ flux }),
  router
}, App));

var serverEntry = {
  router,
  vm,
  flux,
  createRenderer: vueServerRenderer.createRenderer,
  renderOptions: {}
};

module.exports = serverEntry;
