'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var VueRouter = _interopDefault(require('vue-router'));
var Vue = _interopDefault(require('vue'));
var vueServerRenderer = require('vue-server-renderer');

// @NOTICE This file is generated by sav.

// npm i -D vue vue-router
// 全局的VUE组件需要在这里注册
// 其他需要用Vue的需要从这里引入
Vue.use(VueRouter);

var Article = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "page-article" }, [_c('h2', [_vm._v("Article")]), _vm._v(" "), _c('router-view', { staticClass: "view-container" })], 1);
  },
  staticRenderFns: [],
  name: 'Article',
  getters: [],
  actions: []
};

var ArticlePosts = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _vm._m(0);
  },
  staticRenderFns: [function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "article-posts" }, [_c('h2', [_vm._v("ArticlePosts")])]);
  }],
  name: 'ArticlePosts',
  getters: [],
  actions: []
};

var ArticleView = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _vm._m(0);
  },
  staticRenderFns: [function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "article-view" }, [_c('h2', [_vm._v("ArticleView")])]);
  }],
  name: 'ArticleView',
  getters: [],
  actions: []
};

var ArticleModify = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _vm._m(0);
  },
  staticRenderFns: [function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "article-modify" }, [_c('h2', [_vm._v("ArticleModify")])]);
  }],
  name: 'ArticleModify',
  getters: [],
  actions: []
};

var Home = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "page-home" }, [_c('h2', [_vm._v("Home")]), _vm._v(" "), _c('router-view', { staticClass: "view-container" })], 1);
  },
  staticRenderFns: [],
  name: 'Home',
  getters: [],
  actions: []
};

var HomeIndex = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _vm._m(0);
  },
  staticRenderFns: [function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "home-index" }, [_c('h2', [_vm._v("HomeIndex")])]);
  }],
  name: 'HomeIndex',
  getters: [],
  actions: []
};

var HomeAbout = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _vm._m(0);
  },
  staticRenderFns: [function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "home-about" }, [_c('h2', [_vm._v("HomeAbout")])]);
  }],
  name: 'HomeAbout',
  getters: [],
  actions: []
};

var HomeProfile = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _vm._m(0);
  },
  staticRenderFns: [function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { staticClass: "home-profile" }, [_c('h2', [_vm._v("HomeProfile")])]);
  }],
  name: 'HomeProfile',
  getters: [],
  actions: []
};

// @NOTICE This file is generated by sav.

var routes = [{
  component: Article,
  path: "/article",
  children: [{
    component: ArticlePosts,
    name: "ArticlePosts",
    path: "posts"
  }, {
    component: ArticleView,
    name: "ArticleView",
    path: "/articles/:aid"
  }, {
    component: ArticleModify,
    name: "ArticleModify",
    path: "modify/:aid?"
  }, {
    component: ArticleModify,
    name: "ArticleUpdate",
    path: "update/:aid"
  }]
}, {
  component: Home,
  path: "",
  children: [{
    component: HomeIndex,
    name: "HomeIndex",
    path: "/"
  }, {
    component: HomeAbout,
    name: "HomeAbout",
    path: "about"
  }, {
    component: HomeProfile,
    name: "HomeProfile",
    path: "profile/:uid"
  }]
}];

var App = {
  render: function () {
    var _vm = this;var _h = _vm.$createElement;var _c = _vm._self._c || _h;return _c('div', { attrs: { "id": "app" } }, [_c('router-view', { staticClass: "page-container" }), _vm._v(" "), _c('pre', [_vm._v(_vm._s(_vm.$route))])], 1);
  },
  staticRenderFns: [],
  name: 'App',
  getters: [],
  actions: [],
  watch: {
    $route() {
      console.log('route', this.$route);
    }
  }
};

// @NOTICE This file is generated by sav.

// npm i -D vue-server-renderer
let router = new VueRouter(Object.assign({
  mode: 'history',
  routes,
  linkActiveClass: 'is-active'
}));

let vm = new Vue(Object.assign({
  router
}, App));

var serverEntry = {
  router,
  vm,
  createRenderer: vueServerRenderer.createRenderer,
  renderOptions: {}
};

module.exports = serverEntry;
