// import path from 'path'
import fs from 'fs'
import {ensureDir, outputFile, pathExists} from 'fs-extra'

export function inputFile (file) {
  return new Promise((resolve, reject) => {
    fs.readFile(file, (err, data) => {
      return err ? reject(err) : resolve(data)
    })
  })
}

export function readDir (dir) {
  return new Promise((resolve, reject) => {
    fs.readdir(dir, (err, data) => {
      return err ? reject(err) : resolve(data)
    })
  })
}

export {
  pathExists,
  ensureDir,
  outputFile
}

export const noticeString = '// @NOTICE This file is generated by sav.\n\n'
