import path from 'path'
import fs from 'fs'
import {ensureDir, outputFile, pathExists} from 'fs-extra'

export function inputFile (file) {
  return new Promise((resolve, reject) => {
    fs.readFile(file, (err, data) => {
      return err ? reject(err) : resolve(data)
    })
  })
}

export function readDir (dir) {
  return new Promise((resolve, reject) => {
    fs.readdir(dir, (err, data) => {
      return err ? reject(err) : resolve(data)
    })
  })
}

export {
  pathExists,
  ensureDir,
  outputFile
}

export const noticeString = '// @NOTICE This file is generated by sav.\n\n'

/**
 * 判断是否客户端界面模块
 * @param  {Object}  modal 模块定义
 * @return {Boolean}
 */
export function isClientView (modal) {
  // modal 被定义为 view 类型的 modal
  if (modal.view) {
    return true
  }
  if (modal.routes.filter(it => it.view).length) {
    return true
  }
}

/**
 * 判断是否是客户端路由
 * @param  {Object} modal 模块定义
 * @param  {Object} route 路由定义
 * @return {Boolean}
 */
export function isClientRouter (modal, route) {
  if (modal.view) {
    return !(route.view === false || Number(route.view) === 0)
  }
  return !!route.view
}

export async function putDirFileContent (dir, opts, fileName, fileData) {
  let filePath = path.resolve(dir, fileName)
  if (opts.force || !await pathExists(filePath)) {
    await outputFile(filePath, fileData)
  }
}
