// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  ReqAccountLogin: {
    props: {
      userId: "String",
      password: "String"
    }
  },
  Sex: {
    default: 1,
    enums: [
      {
        key: "male",
        value: 1
      },
      {
        key: "female",
        value: 2
      }
    ]
  },
  ResHomeIndex: {
    res: {
      welcome: "Hello World"
    },
    props: {
      welcome: "String"
    }
  },
  ResHomeAbout: {
    props: {
      aboutInfo: "String"
    }
  }
}
