// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  moduleName: "Article",
  moduleGroup: "Api",
  props: {
    routePrefix: "api"
  },
  routes: [
    {
      actionName: "comment",
      middlewares: [
        {
          name: "req",
          props: {
            props: {
              aid: "String",
              content: "String"
            }
          }
        },
        {
          name: "route",
          props: {
            method: "POST",
            path: "comment/:aid"
          }
        },
        {
          name: "res",
          props: {
            props: {
              aid: "String",
              content: "String",
              createdAt: "String"
            }
          }
        }
      ]
    }
  ]
}
