// @NOTICE This file is generated by sav-cli.

module.exports = {
  moduleName: "Article",
  moduleGroup: "Api",
  uri: "ArticleApi",
  props: {
    routePrefix: "api"
  },
  routes: [
    {
      actionName: "comment",
      uri: "ArticleApi.comment",
      middlewares: [
        {
          name: "req",
          props: {
            props: {
              aid: "String",
              content: "String"
            }
          }
        },
        {
          name: "route",
          props: {
            methods: [
              "POST"
            ],
            path: "comment/:aid"
          }
        },
        {
          name: "res",
          props: {
            props: {
              aid: "String",
              content: "String",
              createdAt: "String"
            }
          }
        }
      ]
    }
  ],
  SavRoute: {
    uri: "ArticleApi",
    path: "/api/article",
    childs: [
      {
        uri: "ArticleApi.comment",
        path: "/api/article/comment/:aid",
        methods: [
          "POST"
        ],
        relative: "comment/:aid"
      }
    ],
    parents: []
  }
}
