// @NOTICE This file is generated by sav-cli 

export default {
  postApiArticleComment: {
    path: "/api/article/comment/:aid",
    method: "POST"
  },
  getAccountLogin: {
    path: "/account/login",
    method: "GET"
  },
  postAccountPostLogin: {
    path: "/account/postLogin",
    method: "POST"
  },
  getAccountRegister: {
    path: "/account/register",
    method: "GET"
  },
  postAccountPostRegister: {
    path: "/account/postRegister",
    method: "POST"
  },
  getArticlePosts: {
    path: "/article/posts",
    method: "GET"
  },
  getArticleView: {
    path: "/article/view/:aid",
    method: "GET"
  },
  getArticleModify: {
    path: "/article/modify/:id?",
    method: "GET"
  },
  postArticleUpdate: {
    path: "/article/update/:aid",
    method: "POST"
  },
  getHomeIndex: {
    path: "/",
    method: "GET"
  },
  getHomeAbout: {
    path: "/about",
    method: "GET"
  }
}
