// @NOTICE This file is generated by sav-cli 

export default {
  pOSTApiArticleComment: {
    path: "/api/article/comment/:aid",
    method: "POST"
  },
  gETAccountLogin: {
    path: "/account/login",
    method: "GET"
  },
  pOSTAccountPostLogin: {
    path: "/account/postLogin",
    method: "POST"
  },
  gETAccountRegister: {
    path: "/account/register",
    method: "GET"
  },
  pOSTAccountPostRegister: {
    path: "/account/postRegister",
    method: "POST"
  },
  gETArticlePosts: {
    path: "/article/posts",
    method: "GET"
  },
  gETArticleView: {
    path: "/article/view/:aid",
    method: "GET"
  },
  gETArticleModify: {
    path: "/article/modify/:id?",
    method: "GET"
  },
  pOSTArticleUpdate: {
    path: "/article/update/:aid",
    method: "POST"
  },
  gETHomeIndex: {
    path: "/",
    method: "GET"
  },
  gETHomeAbout: {
    path: "/about",
    method: "GET"
  }
}
