// @NOTICE This file is generated by sav-cli.

/* eslint quotes: ["off"] */
module.exports = {
  path: "",
  routes: {
    index: {
      method: "GET",
      path: "/",
      title: "主页",
      keywords: "关键字列表",
      description: "页面描述"
    },
    about: {
      method: "GET",
      keywords: "关键字列表",
      description: "页面描述",
      title: "关于我们"
    },
    profile: {
      method: "GET",
      path: "profile/:uid"
    },
    userInfo: {
      method: "GET",
      vue: false
    },
    navMenu: {
      method: "GET",
      vue: false
    }
  }
}
