// @NOTICE This file is generated by sav.

module.exports = {
  ResHomeNavMenu: {
    props: {
      menus: "Array<NavMenuItem>"
    },
    refs: {
      NavMenuItem: {
        props: {
          title: "String",
          url: "String"
        }
      }
    }
  },
  ResHomeUserInfo: {
    props: {
      userInfo: "UserInfo"
    },
    refs: {
      Role: {
        name: "Role",
        default: "guest",
        enums: [
          {
            key: "user",
            value: "user"
          },
          {
            key: "guest",
            value: "guest"
          },
          {
            key: "admin",
            value: "admin"
          }
        ]
      },
      UserInfo: {
        props: {
          name: "String",
          id: "Number",
          role: "Role"
        }
      }
    }
  },
  ReqAccountLogin: {
    props: {
      userId: "String",
      password: "String"
    }
  },
  Sex: {
    default: 1,
    enums: [
      {
        key: "male",
        value: 1
      },
      {
        key: "female",
        value: 2
      }
    ]
  },
  ResHomeIndex: {
    res: {
      welcome: "Hello World"
    },
    props: {
      welcome: "String"
    }
  },
  ResHomeAbout: {
    props: {
      aboutInfo: "String"
    }
  },
  ResHomeProfile: {
    props: {
      userProfile: "UserProfile"
    },
    refs: {
      UserProfile: {
        props: {
          id: "Number",
          name: "String"
        }
      }
    }
  }
}
